import type { Lead } from "@/types/lead";

const salesManager = { name: "Nimal Kumara", role: "Sales Manager", initials: "NK" };

export const initialLeads: Lead[] = [
  { id: "lead-2026-108", name: "Samantha Dias", phone: "+94 77 234 5678", email: "samantha@email.com", location: "Battaramulla, WP", source: "Web Inquiry", projectType: "Residential Villa", projectSummary: "3BR Villa · Battaramulla · Web inquiry", bedrooms: "3BR + Study", budget: "LKR 12–15M", budgetValue: 13_500_000, timeline: "Start Q3 2026", status: "Contacted", createdAtLabel: "Today", notes: "Client prefers a modern minimalist design on an existing 10-perch plot. Interior design consultation is also required.", assignedTo: salesManager, activities: [{ id: "a1", kind: "call", description: "Initial phone call — discussed requirements and budget", occurredAt: "Today, 10:30 AM" }, { id: "a2", kind: "email", description: "Lead captured via web form inquiry", occurredAt: "Today, 9:15 AM" }] },
  { id: "lead-2026-107", name: "Ravi Jayasuriya", phone: "+94 71 882 9041", email: "ravi.j@lankamail.lk", location: "Colombo 3, WP", source: "Referral", projectType: "Commercial Office", projectSummary: "Commercial Office · Colombo 3 · Referral", bedrooms: "—", budget: "LKR 32–40M", budgetValue: 36_000_000, timeline: "Start Q4 2026", status: "Qualified", createdAtLabel: "Yesterday", notes: "Fit-out for a growing professional services firm. Requires space planning and a detailed cost proposal.", assignedTo: salesManager, activities: [{ id: "a3", kind: "note", description: "Site visit scheduled with the client", occurredAt: "Yesterday, 3:45 PM" }] },
  { id: "lead-2026-106", name: "Priya Mendis", phone: "+94 76 441 2098", email: "priya.mendis@email.com", location: "Kandy, CP", source: "Phone Inquiry", projectType: "Residential House", projectSummary: "4BR House · Kandy · Phone inquiry", bedrooms: "4BR", budget: "LKR 18–22M", budgetValue: 20_000_000, timeline: "Start Q1 2027", status: "New", createdAtLabel: "Apr 10", notes: "Early-stage inquiry for a family home. The land survey is expected next month.", assignedTo: salesManager, activities: [{ id: "a4", kind: "call", description: "Inbound inquiry captured by reception", occurredAt: "Apr 10, 2:20 PM" }] },
  { id: "lead-2026-105", name: "Thilak Wickramasinghe", phone: "+94 77 902 1180", email: "thilak.w@email.com", location: "Galle, SP", source: "Exhibition", projectType: "Luxury Villa", projectSummary: "Luxury Villa · Galle · Exhibition", bedrooms: "5BR", budget: "LKR 45–55M", budgetValue: 50_000_000, timeline: "Start Q4 2026", status: "Contacted", createdAtLabel: "Apr 9", notes: "Coastal property requiring premium finishes, landscaping and sustainability options.", assignedTo: salesManager, activities: [{ id: "a5", kind: "email", description: "Company portfolio and consultation slots sent", occurredAt: "Apr 9, 4:10 PM" }] },
  { id: "lead-2026-104", name: "Ayesha Niroshan", phone: "+94 75 330 1144", email: "ayesha.n@email.com", location: "Nugegoda, WP", source: "Email Inquiry", projectType: "Apartment Renovation", projectSummary: "Apartment · Nugegoda · Email inquiry", bedrooms: "3BR", budget: "LKR 7–9M", budgetValue: 8_000_000, timeline: "In progress", status: "Converted", createdAtLabel: "Apr 7", notes: "Converted after design consultation. Quotation preparation has started.", assignedTo: salesManager, activities: [{ id: "a6", kind: "note", description: "Lead approved and converted to quotation", occurredAt: "Apr 11, 11:00 AM" }] },
  { id: "lead-2026-103", name: "Lakshan Fernando", phone: "+94 72 550 1933", email: "lakshan@fernholdings.lk", location: "Ja-Ela, WP", source: "Walk-in", projectType: "Industrial Warehouse", projectSummary: "Industrial Warehouse · Ja-Ela · Walk-in", bedrooms: "—", budget: "LKR 24–30M", budgetValue: 27_000_000, timeline: "Start Q3 2026", status: "Qualified", createdAtLabel: "Apr 5", notes: "Warehouse with loading bay, office area and future expansion provision.", assignedTo: salesManager, activities: [{ id: "a7", kind: "call", description: "Technical consultation completed", occurredAt: "Apr 8, 9:30 AM" }] },
  { id: "lead-2026-102", name: "Manjula Rathnayake", phone: "+94 70 881 5570", email: "manjula.r@email.com", location: "Moratuwa, WP", source: "Web Inquiry", projectType: "Apartment Renovation", projectSummary: "2BR Apartment · Moratuwa · Web inquiry", bedrooms: "2BR", budget: "LKR 4–6M", budgetValue: 5_000_000, timeline: "On hold", status: "Lost", createdAtLabel: "Apr 2", notes: "Client selected an alternative supplier due to timeline constraints.", assignedTo: salesManager, activities: [{ id: "a8", kind: "note", description: "Opportunity marked as lost", occurredAt: "Apr 6, 5:20 PM" }] },
];
