"use client";

import { FormEvent, useEffect, useMemo, useState } from "react";
import { Check, Clock3, DollarSign, Filter, Mail, MessageSquareText, Phone, Plus, RefreshCcw, Search, UserRound, Users, X } from "lucide-react";
import { initialLeads } from "./leadData";
import { createLead as createLeadRequest, getLead, listLeads, updateLeadStatus } from "./leadApi";
import type { Lead, LeadStatus } from "@/types/lead";

const statuses: ("All Leads" | LeadStatus)[] = ["All Leads", "New", "Contacted", "Qualified", "Converted", "Lost"];
const avatarStyles = ["from-blue-600 to-blue-800", "from-emerald-600 to-emerald-800", "from-violet-600 to-violet-800", "from-amber-600 to-amber-800", "from-red-600 to-red-800", "from-cyan-600 to-cyan-800", "from-slate-500 to-slate-700"];
const fieldClass = "mt-1.5 w-full rounded-lg border border-outline-variant bg-surface-container-lowest px-3 py-2.5 text-sm outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/10";

function initials(name: string) { return name.split(/\s+/).map((word) => word[0]).join("").slice(0, 2).toUpperCase(); }
function formatPipeline(value: number) { return value >= 1_000_000 ? `LKR ${Math.round(value / 1_000_000)}M` : `LKR ${value.toLocaleString()}`; }

function StatusBadge({ status }: { status: LeadStatus }) {
  const styles: Record<LeadStatus, string> = { New: "border-outline-variant bg-surface-container text-on-surface-variant", Contacted: "border-amber-200 bg-risk-medium-container text-amber-700", Qualified: "border-blue-200 bg-primary-soft text-primary", Converted: "border-emerald-200 bg-risk-low-container text-emerald-700", Lost: "border-error-outline bg-error-container text-error" };
  return <span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-[11px] font-semibold ${styles[status]}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{status}</span>;
}

function MetricCard({ icon: Icon, value, label, tone }: { icon: typeof Users; value: string; label: string; tone: string }) {
  return <article className="flex items-center gap-3 rounded-xl border border-outline-variant bg-surface-container-lowest px-4 py-3.5 shadow-level-1"><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-lg ${tone}`}><Icon size={19} /></div><div><p className="font-mono text-xl font-bold">{value}</p><p className="text-[11.5px] text-on-surface-muted">{label}</p></div></article>;
}

function LeadModal({ onClose, onCreate }: { onClose: () => void; onCreate: (lead: Lead) => Promise<void> }) {
  const [error, setError] = useState(""); const [submitting, setSubmitting] = useState(false);
  const submit = async (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const data = new FormData(event.currentTarget);
    const name = String(data.get("name") ?? "").trim(); const phone = String(data.get("phone") ?? "").trim();
    if (!name || !phone) { setError("Client name and phone number are required."); return; }
    const projectType = String(data.get("projectType")); const location = String(data.get("location") || "Not specified"); const source = String(data.get("source")); const budgetValue = Number(data.get("budget")) || 0;
    setSubmitting(true); setError("");
    try { await onCreate({ id: `lead-${Date.now()}`, name, phone, email: String(data.get("email") ?? ""), location, source, projectType, projectSummary: `${projectType} · ${location} · ${source}`, bedrooms: "—", budget: budgetValue ? formatPipeline(budgetValue) : "Not specified", budgetValue, timeline: String(data.get("timeline") || "To be confirmed"), notes: String(data.get("notes") ?? ""), status: "New", createdAtLabel: "Just now", assignedTo: { name: "Nimal Kumara", role: "Sales Manager", initials: "NK" }, activities: [{ id: `activity-${Date.now()}`, kind: "note", description: `Lead captured via ${source.toLowerCase()}`, occurredAt: "Just now" }] }); } catch (requestError) { setError(requestError instanceof Error ? requestError.message : "The lead could not be created."); } finally { setSubmitting(false); }
  };
  return <div className="fixed inset-0 z-[70] flex items-center justify-center bg-slate-950/45 p-4" role="dialog" aria-modal="true" aria-labelledby="capture-lead-title" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><form onSubmit={submit} className="max-h-[92vh] w-full max-w-2xl overflow-y-auto rounded-2xl border border-outline-variant bg-white shadow-level-2">
    <div className="sticky top-0 z-10 flex items-center justify-between border-b border-outline-variant bg-white px-5 py-4"><div><h2 id="capture-lead-title" className="text-lg font-bold">Capture a new lead</h2><p className="text-xs text-on-surface-muted">Add contact and project requirements.</p></div><button type="button" onClick={onClose} aria-label="Close dialog" className="rounded-lg p-2 hover:bg-surface-container"><X size={18} /></button></div>
    <div className="grid gap-4 p-5 sm:grid-cols-2">
      <label className="text-xs font-semibold">Client name *<input name="name" className={fieldClass} placeholder="e.g. Kamal Perera" autoFocus /></label><label className="text-xs font-semibold">Phone number *<input name="phone" className={fieldClass} placeholder="+94 77 123 4567" /></label>
      <label className="text-xs font-semibold">Email<input name="email" type="email" className={fieldClass} placeholder="client@email.com" /></label><label className="text-xs font-semibold">Location<input name="location" className={fieldClass} placeholder="City, province" /></label>
      <label className="text-xs font-semibold">Project type<select name="projectType" className={fieldClass}><option>Residential Villa</option><option>Residential House</option><option>Commercial Office</option><option>Apartment Renovation</option><option>Industrial Warehouse</option></select></label><label className="text-xs font-semibold">Lead source<select name="source" className={fieldClass}><option>Web Inquiry</option><option>Phone Inquiry</option><option>Referral</option><option>Walk-in</option><option>Exhibition</option><option>Email Inquiry</option></select></label>
      <label className="text-xs font-semibold">Estimated budget (LKR)<input name="budget" type="number" min="0" className={fieldClass} placeholder="15000000" /></label><label className="text-xs font-semibold">Expected timeline<input name="timeline" className={fieldClass} placeholder="e.g. Start Q4 2026" /></label>
      <label className="text-xs font-semibold sm:col-span-2">Notes<textarea name="notes" rows={3} className={fieldClass} placeholder="Design preferences, land details, or other requirements" /></label>{error ? <p className="text-sm text-error sm:col-span-2" role="alert">{error}</p> : null}
    </div><div className="flex justify-end gap-2 border-t border-outline-variant px-5 py-4"><button type="button" onClick={onClose} className="rounded-lg border border-outline-variant px-4 py-2 text-sm font-semibold hover:bg-surface-container">Cancel</button><button type="submit" disabled={submitting} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-semibold text-white hover:bg-primary-hover disabled:opacity-60">{submitting ? <RefreshCcw size={15} className="animate-spin" /> : <Plus size={15} />}{submitting ? "Saving..." : "Capture Lead"}</button></div>
  </form></div>;
}

function Field({ label, value, accent = false }: { label: string; value: string; accent?: boolean }) { return <div className="min-w-0"><p className="text-[11px] text-on-surface-muted">{label}</p><p className={`mt-0.5 break-words text-xs font-medium ${accent ? "font-mono text-primary" : ""}`}>{value}</p></div>; }

function DetailPanel({ lead, onStatusChange }: { lead: Lead; onStatusChange: (status: LeadStatus) => void }) {
  return <aside className="overflow-hidden rounded-xl border border-outline-variant bg-white shadow-level-1"><div className="relative overflow-hidden bg-gradient-to-br from-blue-700 to-slate-900 p-5 text-white"><div className="absolute -right-8 -top-8 h-32 w-32 rounded-full bg-white/5" /><div className="flex h-12 w-12 items-center justify-center rounded-full bg-white/20 text-base font-bold">{initials(lead.name)}</div><h2 className="mt-2.5 text-base font-bold">{lead.name}</h2><p className="mt-0.5 text-xs text-white/65">{lead.projectType} · {lead.location}</p><div className="mt-3 flex gap-2"><span className="rounded-full bg-white/15 px-2.5 py-1 text-[11px] font-semibold">{lead.status}</span><span className="rounded-full bg-white/15 px-2.5 py-1 text-[11px] font-semibold">{lead.source}</span></div></div>
    <div className="divide-y divide-outline-variant"><section className="p-5"><h3 className="mb-3 text-[10px] font-bold uppercase tracking-[.08em] text-on-surface-muted">Contact information</h3><div className="grid grid-cols-2 gap-3"><Field label="Phone" value={lead.phone} /><Field label="Email" value={lead.email || "—"} /><Field label="Location" value={lead.location} /><Field label="Source" value={lead.source} /></div></section>
      <section className="p-5"><h3 className="mb-3 text-[10px] font-bold uppercase tracking-[.08em] text-on-surface-muted">Project requirements</h3><div className="grid grid-cols-2 gap-3"><Field label="Type" value={lead.projectType} /><Field label="Bedrooms" value={lead.bedrooms} /><Field label="Est. budget" value={lead.budget} accent /><Field label="Timeline" value={lead.timeline} /></div>{lead.notes ? <div className="mt-3"><p className="text-[11px] text-on-surface-muted">Notes</p><p className="mt-1 text-xs leading-5 text-on-surface-variant">{lead.notes}</p></div> : null}</section>
      <section className="p-5"><h3 className="mb-3 text-[10px] font-bold uppercase tracking-[.08em] text-on-surface-muted">Activity timeline</h3><div className="space-y-4">{lead.activities.map((activity) => { const Icon = activity.kind === "call" ? Phone : activity.kind === "email" ? Mail : MessageSquareText; return <div key={activity.id} className="flex gap-3"><div className="flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-primary-soft text-primary"><Icon size={13} /></div><div><p className="text-xs font-medium leading-5">{activity.description}</p><p className="text-[11px] text-on-surface-muted">{activity.occurredAt}</p></div></div>; })}</div></section>
      <section className="p-5"><h3 className="mb-3 text-[10px] font-bold uppercase tracking-[.08em] text-on-surface-muted">Assigned to</h3><div className="flex items-center gap-2.5"><div className="flex h-8 w-8 items-center justify-center rounded-full bg-gradient-to-br from-blue-600 to-blue-800 text-[11px] font-bold text-white">{lead.assignedTo.initials}</div><div><p className="text-xs font-semibold">{lead.assignedTo.name}</p><p className="text-[11px] text-on-surface-muted">{lead.assignedTo.role}</p></div></div></section></div>
    <div className="flex gap-2 border-t border-outline-variant p-4"><a href={`tel:${lead.phone}`} className="flex flex-1 items-center justify-center gap-2 rounded-lg border border-outline-variant px-3 py-2 text-xs font-semibold hover:bg-surface-container"><Phone size={14} />Call</a><select value={lead.status} onChange={(event) => onStatusChange(event.target.value as LeadStatus)} aria-label="Update lead status" className="min-w-0 flex-1 rounded-lg bg-primary px-2 py-2 text-xs font-semibold text-white outline-none"><option>New</option><option>Contacted</option><option>Qualified</option><option>Converted</option><option>Lost</option></select></div></aside>;
}

export default function LeadsDashboardClient() {
  const [leads, setLeads] = useState(initialLeads); const [selectedId, setSelectedId] = useState(initialLeads[0].id); const [activeStatus, setActiveStatus] = useState<(typeof statuses)[number]>("All Leads"); const [query, setQuery] = useState(""); const [showModal, setShowModal] = useState(false); const [loading, setLoading] = useState(true); const [usingPreview, setUsingPreview] = useState(false); const [feedback, setFeedback] = useState("");
  useEffect(() => { let active = true; listLeads({ page: 1, limit: 100, sortBy: "createdAt", sortOrder: "desc" }).then(({ leads: liveLeads }) => { if (!active) return; if (liveLeads.length) { setLeads(liveLeads); setSelectedId(liveLeads[0].id); setUsingPreview(false); } else { setUsingPreview(true); } }).catch(() => { if (active) setUsingPreview(true); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const filtered = useMemo(() => leads.filter((lead) => (activeStatus === "All Leads" || lead.status === activeStatus) && `${lead.name} ${lead.projectSummary} ${lead.email} ${lead.phone}`.toLowerCase().includes(query.toLowerCase())), [leads, activeStatus, query]);
  const selected = filtered.find((lead) => lead.id === selectedId) ?? filtered[0] ?? null; const converted = leads.filter((lead) => lead.status === "Converted").length; const followUp = leads.filter((lead) => lead.status === "Contacted" || lead.status === "Qualified").length;
  const selectLead = async (id: string) => { setSelectedId(id); if (usingPreview) return; try { const detail = await getLead(id); setLeads((items) => items.map((lead) => lead.id === id ? detail : lead)); } catch { setFeedback("Lead details could not be refreshed. Showing the available list data."); } };
  const updateStatus = async (status: LeadStatus) => { if (!selected) return; const previous = selected.status; setLeads((items) => items.map((lead) => lead.id === selected.id ? { ...lead, status } : lead)); if (usingPreview) { setFeedback("Preview mode: the status was updated locally."); return; } try { const updated = await updateLeadStatus(selected.id, status); setLeads((items) => items.map((lead) => lead.id === selected.id ? { ...lead, ...updated } : lead)); setFeedback("Lead status updated successfully."); } catch (error) { setLeads((items) => items.map((lead) => lead.id === selected.id ? { ...lead, status: previous } : lead)); setFeedback(error instanceof Error ? error.message : "The lead status could not be updated."); } };
  const createLead = async (lead: Lead) => { if (usingPreview) { setLeads((items) => [lead, ...items]); setFeedback("Preview mode: the lead was added locally because the backend is unavailable."); } else { const created = await createLeadRequest({ name: lead.name, phone: lead.phone, email: lead.email, location: lead.location, source: lead.source, projectType: lead.projectType, estimatedBudget: lead.budgetValue, timeline: lead.timeline, notes: lead.notes }); lead = created; setLeads((items) => [created, ...items]); setFeedback("Lead created successfully."); } setSelectedId(lead.id); setActiveStatus("All Leads"); setShowModal(false); };
  return <div className="space-y-4">{loading ? <div className="flex items-center gap-2 rounded-lg border border-outline-variant bg-white px-4 py-3 text-xs text-on-surface-variant"><RefreshCcw size={14} className="animate-spin" />Loading leads from the backend...</div> : null}{usingPreview ? <div className="rounded-lg border border-amber-200 bg-risk-medium-container px-4 py-3 text-xs text-amber-800">The Leads API is unavailable or returned no usable records. Showing the built-in preview data.</div> : null}{feedback ? <button type="button" onClick={() => setFeedback("")} className="w-full rounded-lg border border-blue-200 bg-primary-soft px-4 py-3 text-left text-xs text-primary">{feedback} <span className="float-right">Dismiss</span></button> : null}<section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><MetricCard icon={Users} value={String(leads.length)} label="Total Leads" tone="bg-primary-soft text-primary" /><MetricCard icon={Clock3} value={String(followUp)} label="Follow-up Due" tone="bg-risk-medium-container text-amber-600" /><MetricCard icon={Check} value={String(converted)} label="Converted" tone="bg-risk-low-container text-emerald-600" /><MetricCard icon={DollarSign} value={formatPipeline(leads.filter((lead) => lead.status !== "Lost").reduce((sum, lead) => sum + lead.budgetValue, 0))} label="Pipeline Value" tone="bg-violet-50 text-violet-600" /></section>
    <section className="flex flex-col gap-3 xl:flex-row xl:items-center"><div className="flex overflow-x-auto rounded-lg border border-outline-variant bg-white">{statuses.map((status) => <button key={status} type="button" onClick={() => setActiveStatus(status)} className={`shrink-0 px-3.5 py-2 text-xs font-medium ${activeStatus === status ? "bg-primary text-white" : "text-on-surface-variant hover:bg-surface-container"}`}>{status}</button>)}</div><div className="flex flex-1 flex-wrap items-center gap-2 xl:justify-end"><label className="flex h-9 min-w-[190px] flex-1 items-center gap-2 rounded-lg border border-outline-variant bg-white px-3 xl:max-w-[260px]"><Search size={14} className="text-on-surface-muted" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search leads..." className="w-full bg-transparent text-xs outline-none" /></label><button type="button" className="inline-flex h-9 items-center gap-2 rounded-lg border border-outline-variant bg-white px-3 text-xs font-semibold text-on-surface-variant hover:bg-surface-container"><Filter size={14} />Filter</button><button type="button" onClick={() => setShowModal(true)} className="inline-flex h-9 items-center gap-2 rounded-lg bg-primary px-4 text-xs font-semibold text-white hover:bg-primary-hover"><Plus size={15} />Capture Lead</button></div></section>
    <section className="grid items-start gap-4 xl:grid-cols-[minmax(0,1fr)_340px]"><div className="overflow-hidden rounded-xl border border-outline-variant bg-white shadow-level-1"><div className="border-b border-outline-variant bg-surface-container px-5 py-3 text-[10px] font-bold uppercase tracking-[.08em] text-on-surface-muted">Client name & details <span className="font-normal normal-case tracking-normal">({filtered.length})</span></div>{filtered.length ? filtered.map((lead, index) => <button type="button" key={lead.id} onClick={() => selectLead(lead.id)} className={`flex w-full items-center gap-3 border-b border-outline-variant px-4 py-3 text-left last:border-b-0 hover:bg-surface-container ${selected?.id === lead.id ? "border-l-[3px] border-l-primary bg-primary-soft" : "border-l-[3px] border-l-transparent"}`}><div className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-gradient-to-br text-xs font-bold text-white ${avatarStyles[index % avatarStyles.length]}`}>{initials(lead.name)}</div><div className="min-w-0 flex-1"><p className="truncate text-[13.5px] font-semibold">{lead.name}</p><p className="mt-0.5 truncate text-[11.5px] text-on-surface-muted">{lead.projectSummary}</p></div><div className="shrink-0 text-right"><StatusBadge status={lead.status} /><p className="mt-1.5 text-[10.5px] text-on-surface-muted">{lead.createdAtLabel}</p></div></button>) : <div className="px-6 py-16 text-center"><UserRound className="mx-auto text-on-surface-subtle" size={30} /><p className="mt-3 text-sm font-semibold">No leads found</p><p className="mt-1 text-xs text-on-surface-muted">Try another search or status filter.</p></div>}</div>{selected ? <DetailPanel lead={selected} onStatusChange={updateStatus} /> : null}</section>{showModal ? <LeadModal onClose={() => setShowModal(false)} onCreate={createLead} /> : null}</div>;
}
