name: Frontend CI

on:
  push:
    branches:
      - develop
      - main
      - "feature/**"
      - "fix/**"

  pull_request:
    branches:
      - develop
      - main

jobs:
  frontend-ci:
    uses: ConstructPro-ERP/infra/.github/workflows/frontend-ci.yml@v1
